language: java
jdk:
  - openjdk13

addons:
  sonarcloud:
    organization: "marcomarcucci30"
    token: 825dd03189bab41b78bac9d7e5e969805ce6e1f1

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Dsonar.projectKey=marcomarcucci30_openjpa